const FETCH_TO_DOS_START = '[TO_DO]/FETCH_TO_DOS_START';
const FETCH_TO_DOS_FAILED = '[TO_DO]/FETCH_TO_DOS_FAILED';
const FETCH_TO_DOS_SUCCEDED = '[TO_DO]/FETCH_TO_DOS_SUCCEDED';

export default { FETCH_TO_DOS_START, FETCH_TO_DOS_FAILED, FETCH_TO_DOS_SUCCEDED }